[build]
  # Build command to generate static files
  command = "python build.py"
  
  # Directory to publish (where the static files will be generated)
  publish = "dist"
  
  # Python version for Netlify Functions
  environment = { PYTHON_VERSION = "3.11" }

[build.environment]
  PYTHON_VERSION = "3.11"

# Redirect rules for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Catch-all redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Functions configuration
[functions]
  directory = "netlify/functions"
